apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: messages.myorg.dev
spec:
  group: myorg.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                text:
                  type: string
                  description: "메시지 내용"
                  minLength: 1
              required:
                - text
            status:
              type: object
              properties:
                phase:
                  type: string
                lastUpdated:
                  type: string
                  format: date-time
      additionalPrinterColumns:
        - name: Text
          type: string
          jsonPath: .spec.text
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: messages
    singular: message
    kind: Message