apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-message-operator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-message-operator
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["myorg.dev"]
    resources: ["messages"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["myorg.dev"]
    resources: ["messages/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["myorg.dev"]
    resources: ["messages/finalizers"]
    verbs: ["update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: go-message-operator-binding
subjects:
  - kind: ServiceAccount
    name: go-message-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: go-message-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-message-operator
  namespace: default
  labels:
    app: go-message-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-message-operator
  template:
    metadata:
      labels:
        app: go-message-operator
    spec:
      serviceAccountName: go-message-operator
      containers:
        - name: manager
          image: gcr.io/YOUR_PROJECT_ID/go-message-operator:latest
          imagePullPolicy: Always
          command:
            - /manager
          args:
            - --leader-elect=false
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65532
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault