apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: messages.myorg.dev
spec:
  group: myorg.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                text:
                  type: string
                  description: "메시지 내용"
              required:
                - text
            status:
              type: object
  scope: Namespaced
  names:
    plural: messages
    singular: message
    kind: Message