apiVersion: v1
kind: ServiceAccount
metadata:
  name: message-operator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: message-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["myorg.dev"]
    resources: ["messages"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: message-operator-binding
subjects:
  - kind: ServiceAccount
    name: message-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: message-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-operator
  namespace: default
  labels:
    app: message-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-operator
  template:
    metadata:
      labels:
        app: message-operator
    spec:
      serviceAccountName: message-operator
      containers:
        - name: operator
          image: gcr.io/YOUR_PROJECT_ID/python-operator:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault